// Convert country names to flag emojis
export const countryFlagMap: Record<string, string> = {
    "Morocco": "🇲🇦",
    "Spain": "🇪🇸",
    "South Africa": "🇿🇦",
    "Austria": "🇦🇹",
    "United States": "🇺🇸",
    "Canada": "🇨🇦",
    "United Kingdom": "🇬🇧",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Italy": "🇮🇹",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Switzerland": "🇨🇭",
    "Sweden": "🇸🇪",
    "Norway": "🇳🇴",
    "Denmark": "🇩🇰",
    "Finland": "🇫🇮",
    "Poland": "🇵🇱",
    "Greece": "🇬🇷",
    "Portugal": "🇵🇹",
    "Ireland": "🇮🇪",
    "Czech Republic": "🇨🇿",
    "Hungary": "🇭🇺",
    "Romania": "🇷🇴",
    "Bulgaria": "🇧🇬",
    "Croatia": "🇭🇷",
    "Serbia": "🇷🇸",
    "Ukraine": "🇺🇦",
    "Russia": "🇷🇺",
    "Turkey": "🇹🇷",
    "Israel": "🇮🇱",
    "Saudi Arabia": "🇸🇦",
    "UAE": "🇦🇪",
    "Egypt": "🇪🇬",
    "Nigeria": "🇳🇬",
    "Kenya": "🇰🇪",
    "India": "🇮🇳",
    "Pakistan": "🇵🇰",
    "Bangladesh": "🇧🇩",
    "Sri Lanka": "🇱🇰",
    "Thailand": "🇹🇭",
    "Vietnam": "🇻🇳",
    "Philippines": "🇵🇭",
    "Indonesia": "🇮🇩",
    "Malaysia": "🇲🇾",
    "Singapore": "🇸🇬",
    "Japan": "🇯🇵",
    "South Korea": "🇰🇷",
    "China": "🇨🇳",
    "Taiwan": "🇹🇼",
    "Australia": "🇦🇺",
    "New Zealand": "🇳🇿",
    "Brazil": "🇧🇷",
    "Mexico": "🇲🇽",
    "Argentina": "🇦🇷",
    "Colombia": "🇨🇴",
    "Chile": "🇨🇱",
    "Peru": "🇵🇪",
}

export function getCountryFlag(countryName: string): string {
    return countryFlagMap[countryName] || "🌍"
}

export function formatCountryWithFlag(countryName: string): string {
    return `${getCountryFlag(countryName)} ${countryName}`
}
