// Convert country names to flag emojis
export const countryFlagMap: Record<string, string> = {
    "Morocco": "🇲🇦",
    "Spain": "🇪🇸",
    "South Africa": "🇿🇦",
    "Austria": "🇦🇹",
    "United States": "🇺🇸",
    "Canada": "🇨🇦",
    "United Kingdom": "🇬🇧",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Italy": "🇮🇹",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Switzerland": "🇨🇭",
    "Sweden": "🇸🇪",
    "Norway": "🇳🇴",
    "Denmark": "🇩🇰",
    "Finland": "🇫🇮",
    "Poland": "🇵🇱",
    "Greece": "🇬🇷",
    "Portugal": "🇵🇹",
    "Ireland": "🇮🇪",
    "Czech Republic": "🇨🇿",
    "Hungary": "🇭🇺",
    "Romania": "🇷🇴",
    "Bulgaria": "🇧🇬",
    "Croatia": "🇭🇷",
    "Serbia": "🇷🇸",
    "Ukraine": "🇺🇦",
}

// Country name to ISO code mapping for URL routing
export const countryCodeMap: Record<string, string> = {
    "Morocco": "ma",
    "Spain": "es",
    "South Africa": "za",
    "Austria": "at",
    "United States": "us",
    "Canada": "ca",
    "United Kingdom": "gb",
    "France": "fr",
    "Germany": "de",
    "Italy": "it",
    "Netherlands": "nl",
    "Belgium": "be",
    "Switzerland": "ch",
    "Sweden": "se",
    "Norway": "no",
    "Denmark": "dk",
    "Finland": "fi",
    "Poland": "pl",
    "Greece": "gr",
    "Portugal": "pt",
    "Ireland": "ie",
    "Czech Republic": "cz",
    "Hungary": "hu",
    "Romania": "ro",
    "Bulgaria": "bg",
    "Croatia": "hr",
    "Serbia": "rs",
    "Ukraine": "ua",
    "Russia": "ru",
    "Turkey": "tr",
    "Israel": "il",
    "Saudi Arabia": "sa",
    "UAE": "ae",
    "Egypt": "eg",
    "Nigeria": "ng",
    "Kenya": "ke",
    "India": "in",
    "Pakistan": "pk",
    "Bangladesh": "bd",
    "Sri Lanka": "lk",
    "Thailand": "th",
    "Vietnam": "vn",
    "Philippines": "ph",
    "Indonesia": "id",
    "Malaysia": "my",
    "Singapore": "sg",
    "Japan": "jp",
    "South Korea": "kr",
    "China": "cn",
    "Taiwan": "tw",
    "Australia": "au",
    "New Zealand": "nz",
    "Brazil": "br",
    "Mexico": "mx",
    "Argentina": "ar",
    "Colombia": "co",
    "Chile": "cl",
    "Peru": "pe",
}

export function getCountryFlag(countryName: string): string {
    return countryFlagMap[countryName] || "🌍"
}

export function formatCountryWithFlag(countryName: string): string {
    return `${getCountryFlag(countryName)} ${countryName}`
}
