// Convert country names to flag emojis
export const countryFlagMap: Record<string, string> = {
    "Afghanistan": "🇦🇫",
    "Albania": "🇦🇱",
    "Algeria": "🇩🇿",
    "Angola": "🇦🇴",
    "Argentina": "🇦🇷",
    "Armenia": "🇦🇲",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Bahrain": "🇧🇭",
    "Bangladesh": "🇧🇩",
    "Belgium": "🇧🇪",
    "Brazil": "🇧🇷",
    "Bulgaria": "🇧🇬",
    "Canada": "🇨🇦",
    "Chile": "🇨🇱",
    "China": "🇨🇳",
    "Colombia": "🇨🇴",
    "Costa Rica": "🇨🇷",
    "Croatia": "🇭🇷",
    "Czech Republic": "🇨🇿",
    "Djibouti": "🇩🇯",
    "Dominican Republic": "🇩🇴",
    "Egypt": "🇪🇬",
    "Finland": "🇫🇮",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Greece": "🇬🇷",
    "Hong Kong": "🇭🇰",
    "Hungary": "🇭🇺",
    "India": "🇮🇳",
    "Indonesia": "🇮🇩",
    "Iraq": "🇮🇶",
    "Ireland": "🇮🇪",
    "Italy": "🇮🇹",
    "Japan": "🇯🇵",
    "Jordan": "🇯🇴",
    "Kuwait": "🇰🇼",
    "Lebanon": "🇱🇧",
    "Libya": "🇱🇾",
    "Morocco": "🇲🇦",
    "Oman": "🇴🇲",
    "Palestine": "🇵🇸",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Qatar": "🇶🇦",
    "Romania": "🇷🇴",
    "Russia": "🇷🇺",
    "Saudi Arabia": "🇸🇦",
    "Serbia": "🇷🇸",
    "South Africa": "🇿🇦",
    "Spain": "🇪🇸",
    "Sudan": "🇸🇩",
    "Syria": "🇸🇾",
    "Taiwan": "🇹🇼",
    "Tunisia": "🇹🇳",
    "UAE": "🇦🇪",
    "Ukraine": "🇺🇦",
    "United Kingdom": "🇬🇧",
    "United States": "🇺🇸",
    "United States of America": "🇺🇸",
    "Vietnam": "🇻🇳",
    "Yemen": "🇾🇪",
}

// Country name to ISO code mapping for URL routing
export const countryCodeMap: Record<string, string> = {
    "Afghanistan": "af",
    "Albania": "al",
    "Algeria": "dz",
    "Angola": "ao",
    "Argentina": "ar",
    "Armenia": "am",
    "Australia": "au",
    "Austria": "at",
    "Bahrain": "bh",
    "Bangladesh": "bd",
    "Belgium": "be",
    "Brazil": "br",
    "Bulgaria": "bg",
    "Canada": "ca",
    "Chile": "cl",
    "China": "cn",
    "Colombia": "co",
    "Costa Rica": "cr",
    "Croatia": "hr",
    "Czech Republic": "cz",
    "Djibouti": "dj",
    "Dominican Republic": "do",
    "Egypt": "eg",
    "Finland": "fi",
    "France": "fr",
    "Germany": "de",
    "Greece": "gr",
    "Hong Kong": "hk",
    "Hungary": "hu",
    "India": "in",
    "Indonesia": "id",
    "Iraq": "iq",
    "Ireland": "ie",
    "Italy": "it",
    "Japan": "jp",
    "Jordan": "jo",
    "Kuwait": "kw",
    "Lebanon": "lb",
    "Libya": "ly",
    "Morocco": "ma",
    "Oman": "om",
    "Palestine": "ps",
    "Poland": "pl",
    "Portugal": "pt",
    "Qatar": "qa",
    "Romania": "ro",
    "Russia": "ru",
    "Saudi Arabia": "sa",
    "Serbia": "rs",
    "South Africa": "za",
    "Spain": "es",
    "Sudan": "sd",
    "Syria": "sy",
    "Taiwan": "tw",
    "Tunisia": "tn",
    "UAE": "ae",
    "Ukraine": "ua",
    "United Kingdom": "gb",
    "United States": "us",
    "United States of America": "us",
    "Vietnam": "vn",
    "Yemen": "ye",
}

export function getCountryFlag(countryName: string): string {
    return countryFlagMap[countryName] || "🌍"
}

export function formatCountryWithFlag(countryName: string): string {
    return `${getCountryFlag(countryName)} ${countryName}`
}
